### PR TITLE
os dependent config folder 

### PR DESCRIPTION
**Pull request by moiSentineL**
damn. a lot of things eh?

### CODE REVIEW

**Review by Jonak-Adipta-Kalita — CHANGES_REQUESTED** [review]
in win11, the documents path is inside the "OneDrive" folder inside the user_folder..... this version specific shit is triggering me ;-;

so: if win10\: os.path.expanduser("~/Documents") else if win11\: os.path.expanduser("~/OneDrive/Documents")

if you know what I mean....

**Comment by moiSentineL** [comment]
> in win11, the documents path is inside the "OneDrive" folder inside the user_folder..... this version specific shit is triggering me ;-;
> 
> so: `if win10: os.path.expanduser("~/Documents"); elif win11: os.path.expanduser("~/OneDrive/Documents")`
> 
> if you know what I mean....

sounds like a windows problem

**Comment by moiSentineL** [comment]
I've researched a bit, looks like there are different "versions" of `My Documents` folder path in **both** Win10 and Win11. One is the OneDrive one, and other is the normal user one.

I think we should place the data in `APPDATA` or `LOCALAPPDATA`

**Comment by Jonak-Adipta-Kalita** [comment]
yeah, that makes sense

**Review by Jonak-Adipta-Kalita — APPROVED** [review]
seems good enuff!

**Comment by Jonak-Adipta-Kalita** [comment]
image
these errors are removed with the above commit! good job bro :D

**Pull request merged**
